name: Job-Level Concurrency Test

on:
  pull_request:
    types: [labeled, synchronize]
  
  push:
    branches:
      - master
  
  workflow_dispatch:

# Workflow-level concurrency removed

jobs:
  debug-context:
    runs-on: ubuntu-latest
    # This job won't use concurrency, so it will always run
    steps:
      - name: Debug GitHub Context
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Head ref: ${{ github.head_ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          
      - name: Debug Job Concurrency Groups
        run: |
          echo "Job 1 concurrency group would be: slow-job-1-${{ github.ref != 'refs/heads/master' && github.head_ref || github.sha }}"
          echo "Job 2 concurrency group would be: slow-job-2-${{ github.ref != 'refs/heads/master' && github.head_ref || github.sha }}"

  slow-job-1:
    runs-on: ubuntu-latest
    # Job-level concurrency
    concurrency:
      group: slow-job-1-${{ github.ref != 'refs/heads/master' && github.head_ref || github.sha }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
    steps:
      - name: Run slow task 1
        run: |
          echo "Starting slow job 1..."
          sleep 60
          echo "Slow job 1 completed"

  slow-job-2:
    runs-on: ubuntu-latest
    # Different concurrency group from slow-job-1
    concurrency:
      group: slow-job-2-${{ github.ref != 'refs/heads/master' && github.head_ref || github.sha }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
    steps:
      - name: Run slow task 2
        run: |
          echo "Starting slow job 2..."
          sleep 60
          echo "Slow job 2 completed"
          
  non-concurrent-job:
    runs-on: ubuntu-latest
    # This job has no concurrency settings, so it will always run
    # This matches what you observed in the customer's case where one job succeeded
    steps:
      - name: Run task without concurrency
        run: |
          echo "Starting non-concurrent job..."
          sleep 30
          echo "Non-concurrent job completed"
