name: Concurrency Test

on:
  pull_request:
    types: [labeled, synchronize]
  
  push:
    branches:
      - master
  
  workflow_dispatch:

concurrency:
  group: unit-tests-${{ github.ref != 'refs/heads/master' && github.head_ref || github.sha }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  debug-context:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub Context
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Head ref: ${{ github.head_ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          
      - name: Debug Concurrency Group
        run: |
          echo "Concurrency group: unit-tests-${{ github.ref != 'refs/heads/master' && github.head_ref || github.sha }}"
          echo "Cancel in progress: ${{ github.ref != 'refs/heads/master' }}"

  slow-job-1:
    runs-on: ubuntu-latest
    needs: debug-context
    steps:
      - name: Run slow task 1
        run: |
          echo "Starting slow job 1..."
          sleep 60
          echo "Slow job 1 completed"

  slow-job-2:
    runs-on: ubuntu-latest
    needs: slow-job-1
    steps:
      - name: Run slow task 2
        run: |
          echo "Starting slow job 2..."
          sleep 60
          echo "Slow job 2 completed"
